Es comments
nss-evening-cohort-19/rare-python-server-all-dogs-go-to-kevin pull request #19
Opened 2022-11-04 04:11 UTC by emilyjstroud

Pushing for review

2022-11-04 23:39 UTC, KLaw47 requested changes
pls change comment to comments in the sql for get post comments

2022-11-04 23:39 UTC, KLaw47 commented on views/comment_requests.py
> +        from Comment c
No such table as comment. needs to be comments

2022-11-05 14:09 UTC, KLaw47 approved these changes
looks good

2022-11-05 14:12 UTC, ImadOttallah approved these changes

2022-11-05 14:12 UTC, merged